services:
  - type: web
    name: digiraksha-backend
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
